### ISSUE TITLE
put cluster_config in config.yaml

### ISSUE THREAD

**Issue by jos4uke** [Snakemake-Profiles/slurm#37]
Hi

I would like to ask if it is possible to create a cluster_config key in config.yaml and call it in slurm-submit.py script. It would make it more flexible to update the cluster config file path and thus the profile without touching the source.
Thanks in advance
Jos

**Comment by mwort** [comment]
Hi Jos, I think I know what you are getting at, but I think this wouldnt work for two reasons (correct me if I'm wrong):
1) the `cluster_config` in the profile config.yaml will only be considered if `cluster_config` is not parsed directly to SM. That would mean default parameters would not be considered. Stuff like env variable expansion probably would work either.
2) SM's `cluster_config` argument is officially deprecated since v5.10, i.e. `cluster_config` will soon not be accepted in the profile config.yaml.

Hope that makes sense. This is a cookiecutter template, I wouldnt be too shy changing src files;)

**Comment by jos4uke** [comment]
Hi Michel

sorry for the late reply
You are right, I was thinking `--cluster_config` was deprecated with  v5.10 and soon will be unavailable so it could work for later versions. And I was not aware this will be discarded from config.yaml, only considered the CLI.
Thanks for enlighten me about that.
Best
