### ISSUE TITLE
localrules in profile?

### ISSUE THREAD

**Issue by rneher** [Snakemake-Profiles/slurm#45]
More of a question than an issue: is there a way to specify which rules are to be executed locally in the profile or config? I'd like to make those profile specific as opposed to a `localrules: rule1, rule2` directive in the Snakefile. 

thanks a lot for the fantastic tool and sorry if this is a silly question...

**Comment by percyfal** [comment]
If snakemake had a --localrules option, then one should be able to put it in config.yaml, which probably would be the cleanest solution. Currently, this option is not available in snakemake. Otherwise, one needs to use snakemake.workflow.localrules somehow in slurm-submit.py or slurm_utils.py. You could always try this out in your local profile.

**Comment by percyfal** [comment]
@rneher I'm closing this issue now. Feel free to reopen if you have further queries/suggestions.

**Comment by rneher** [comment]
Thanks for your answer back then. Just leaving what we ended up with here for future reference:

 * define localrules in a file `localrules.smk`
 * add the file to the workflow config like so
   https://github.com/nextstrain/ncov/blob/master/nextstrain_profiles/nextstrain-scicore/scicore-config.yaml#L2 
   https://github.com/nextstrain/ncov/blob/master/nextstrain_profiles/nextstrain-scicore/config.yaml#L4
 * include the file `localrules.smk` in the Snakefile
   https://github.com/nextstrain/ncov/blob/master/Snakefile#L51
