### ISSUE TITLE
Behaviour with the `--cores` snakemake parameter

### ISSUE THREAD

**Issue by tdido** [Snakemake-Profiles/slurm#61]
I've been doing some tests on my cluster with this Snakefile:

```python
rule all:
    input:[f"test.{id}.txt" for id in [1,2]]

rule test:
    output: temp(touch("test.{id}.txt"))
    threads: 40
    shell: "sleep 5"
```
When **not** using the profile, running it with `--cores` set to any of [1,2,60] results in the two instances of the rule running one after the other as I'd expect. Once you set it to 80 or more, both run in parallel.

When using the profile, however, only one will be submitted at a time with `--cores 1`, but both of them will go into the queue with `--cores 2` or higher.

I'd appreciate any help understanding what's going on, and whether it could be with my setup or the way I'm using the profile.

**Comment by tdido** [comment]
It would seem like `--cores` is as confused as I was initially with its equivalente `-j` for jobs: it looks like when using the profile it's actually limiting the number of concurrent jobs, and not the total number of used cores.

**Comment by frankier** [comment]
I agree it's confusing. Trying to map the single node concepts onto a cluster is a bit difficult. One confusing thing is that on a single node `-j/--cores` specifies global parallelism, and `--threads` overrides it for a single rule, but on SLURM it's not clear whether it's possible to specify a global parallelism (as in number of nodes) and then reduce (number of nodes) it for certain jobs. This possibility would be useful for e.g. heterogeneous workflows where we want to limit our parallel GPU usage but don't mind if we request tonnes of single CPU nodes.

**Comment by johanneskoester** [comment]
* indeed, on a cluster , one should write --jobs instead of --cores as specified in the docs. The reason for overloading this arg comes from the history, where snakemake only had a -j, similar to GNU make for defining core usage. I would like to break this up into two options, but that would cause headaches for a lot of other users.
* `--threads` is there to overwrite the threads set in each rule. And this can be used to limit parallelism per rule in a cluster setting.

**Comment by tdido** [comment]
Fantastic. Thanks for the input, @johanneskoester!
