### ISSUE TITLE
using conda with config without global snakemake install

### ISSUE THREAD

**Issue by LZeitler** [Snakemake-Profiles/slurm#75]
When running snakemake through a conda installation, e.g., 
`conda activate snakemake` after installing snakemake in that env and running a workflow with `--use-conda` and specified conda env names in the snakemake rules, snakemake fails completely running the worksflow

```
Traceback (most recent call last):
  File "/storage/homefs/lz20n032/.config/snakemake/slurm/slurm-submit.py", line 7, in <module>
    from snakemake.utils import read_job_properties
ModuleNotFoundError: No module named 'snakemake'
Error submitting jobscript (exit code 1):
```
I suspect that when `slurm-submit.py` is run with `--use-conda`, the original env (`snakemake` in this case) is deactivated and python and subsequently snakemake is reverted back to non conda, whatever is in pythonpath. So it fails to find snakemake and doesn't start at all. 
Some help would be appreciated.

**Comment by LZeitler** [comment]
I ended up creating a fresh conda env, updated snakemake and this profile here, works now

**Comment by GiulioCentorame** [comment]
I am encountering this same issue in the most recent version of Snakemake. I am using checkpoints, so could it be related to https://github.com/snakemake/snakemake/issues/216 ?

**Comment by GiulioCentorame** [comment]
Sorry @jdblischak, I completely missed this! It ended up being an instance of [this StackOverflow issue](https://stackoverflow.com/questions/59493422/snakemake-cluster-script-importerror-snakemake-utils), where the cluster calls snakemake from base, while the workflow calls it from the environment loaded at the time of running it. The (quick and dirty) solution was to update Snakemake in base so that the versions match between the two environments
